/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LinearRegressionSuite extends FunSuite {
  test("everything is ok") {
    assert(1 === 1)
  }
}
